/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.duoc.ui;

import com.duoc.controller.CursoController;
import com.duoc.domain.Colegio;
import com.duoc.domain.Comuna;
import com.duoc.domain.Curso;
import com.duoc.domain.Paquete;
import com.duoc.domain.Region;
import com.duoc.domain.Servicio;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDesktopPane;
import javax.swing.text.DateFormatter;
import javax.swing.text.DefaultFormatterFactory;
import com.duoc.controller.ContratoController;
import com.duoc.domain.Actividadviaje;
import com.duoc.domain.Seguro;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import main.java.com.duoc.util.NumberValidator;

/**
 *
 * @author Rodrigo thrash
 */
public class Contratos extends javax.swing.JInternalFrame {

    CursoController cursocon;
    ContratoController concon;
    JDesktopPane escritorio;
    /**
     * Creates new form Contratos
     */
    public Contratos(JDesktopPane aThis) {
        this.escritorio = aThis;
        initComponents();
        poblarListas();
        setBounds(0,0,escritorio.getWidth(),escritorio.getHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JCBRegion = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        JCBComuna = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        JCBColegio = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        JCBCurso = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        JTFDias = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        JTFNumero = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        JCBPaquetes = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstServicios = new javax.swing.JList();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        JCBAgregarServicio = new javax.swing.JComboBox<>();
        btnQuitarServicio = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstActividades = new javax.swing.JList();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        JCBActividades = new javax.swing.JComboBox<>();
        btnQuitarActividad = new javax.swing.JButton();
        JCBSeguro = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstSeguros = new javax.swing.JList();
        lblTotal = new javax.swing.JLabel();
        JLTotal = new javax.swing.JLabel();
        btnAgregarActividad = new javax.swing.JButton();
        btnAgregarServicio = new javax.swing.JButton();
        txtDate = new javax.swing.JFormattedTextField();
        JBAgregarServicios1 = new javax.swing.JButton();
        btnInsertContrato = new javax.swing.JButton();
        txtTotalContrato = new javax.swing.JTextField();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(960, 500));

        jLabel1.setText("Ingreso de Contratos");

        jLabel2.setText("Region: ");

        JCBRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBRegionActionPerformed(evt);
            }
        });

        jLabel3.setText("Comuna: ");

        jLabel4.setText("Colegio: ");

        jLabel5.setText("Curso: ");

        jLabel6.setText("Dias: ");

        jLabel7.setText("Fecha de viaje: ");

        jLabel8.setText("Numero de alumnos: ");

        jLabel9.setText("Selecione el paquete turistico");

        JCBPaquetes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBPaquetesActionPerformed(evt);
            }
        });

        jLabel10.setText("Paquetes: ");

        jLabel11.setText("Seguro Asociado al contrato");

        jScrollPane1.setViewportView(lstServicios);

        jLabel12.setText("Servicios asociados al paquete turistico");

        jLabel13.setText("Agregar nuevos servicios ");

        JCBAgregarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBAgregarServicioActionPerformed(evt);
            }
        });

        btnQuitarServicio.setText("Quitar");
        btnQuitarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarServicioActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setToolTipText("");

        jScrollPane2.setViewportView(lstActividades);

        jLabel14.setText("Actividades asociadas al paquete turistico");

        jLabel15.setText("Agregar nuevas actividades");

        btnQuitarActividad.setText("Quitar");
        btnQuitarActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarActividadActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(lstSeguros);

        lblTotal.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lblTotal.setText("Total: ");

        btnAgregarActividad.setText("Agregar");
        btnAgregarActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActividadActionPerformed(evt);
            }
        });

        btnAgregarServicio.setText("Agregar");
        btnAgregarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarServicioActionPerformed(evt);
            }
        });

        txtDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });

        JBAgregarServicios1.setText("Agregar");

        btnInsertContrato.setText("Ingresar Contrato");
        btnInsertContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertContratoActionPerformed(evt);
            }
        });

        txtTotalContrato.setText("0");
        txtTotalContrato.setEnabled(false);
        txtTotalContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalContratoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(428, 428, 428)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(jLabel12))
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(JCBSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(JBAgregarServicios1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(27, 27, 27)
                                                .addComponent(jLabel13))
                                            .addComponent(JCBAgregarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnAgregarServicio))
                                        .addGap(49, 49, 49)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(JLTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(lblTotal)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                            .addComponent(txtTotalContrato)
                                                            .addComponent(btnInsertContrato)))
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel14)
                                                                .addGap(50, 50, 50)
                                                                .addComponent(jLabel15))
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(225, 225, 225)
                                                                .addComponent(JCBActividades, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                            .addGap(225, 225, 225)
                                                            .addComponent(btnAgregarActividad)
                                                            .addGap(68, 68, 68)
                                                            .addComponent(btnQuitarActividad))))
                                                .addGap(129, 129, 129))))))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnQuitarServicio)
                                    .addGap(15, 15, 15)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(JCBPaquetes, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(493, 493, 493)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(JCBRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtDate)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(JCBComuna, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(JTFNumero)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(JCBColegio, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(JCBCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(JTFDias, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JCBRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(JCBComuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(JCBColegio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(JCBCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(JTFNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(JCBSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JBAgregarServicios1)
                            .addComponent(jLabel9))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(JCBPaquetes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(jLabel13))
                            .addComponent(jLabel15)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 58, Short.MAX_VALUE)
                                .addComponent(JLTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(JCBAgregarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btnAgregarServicio)
                                            .addComponent(btnQuitarServicio))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(JCBActividades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnQuitarActividad)
                                    .addComponent(btnAgregarActividad))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTotal)
                                    .addComponent(txtTotalContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnInsertContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 937, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JCBRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBRegionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCBRegionActionPerformed

    private void JCBPaquetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBPaquetesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCBPaquetesActionPerformed

    private void JCBAgregarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBAgregarServicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCBAgregarServicioActionPerformed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void btnQuitarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarServicioActionPerformed
        Object selectedServ = lstServicios.getSelectedValue();
        Servicio serv;
        if (selectedServ != null) {
            serv  = (Servicio) selectedServ ;
            DefaultListModel model = (DefaultListModel) lstServicios.getModel(); 
            int index = lstServicios.getSelectedIndex();
            model.remove( index );
            
            Integer valorServicio = serv.getPrecio().intValueExact();
            Integer valorAcumulado = Integer.parseInt(txtTotalContrato.getText()) - valorServicio;
            txtTotalContrato.setText(valorAcumulado.toString());
            
        }else{
             JOptionPane.showMessageDialog(this, "Debes seleccionar un servicio a eliminar!");
        }
    }//GEN-LAST:event_btnQuitarServicioActionPerformed

    private void btnAgregarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarServicioActionPerformed
        Object selectedServ = JCBAgregarServicio.getSelectedItem();
        Servicio serv;
        if (selectedServ != null) {
            serv  = (Servicio) selectedServ ;
            ((DefaultListModel) lstServicios.getModel()).addElement(serv);
            Integer valorServicio = serv.getPrecio().intValueExact();
            Integer valorAcumulado = Integer.parseInt(txtTotalContrato.getText()) + valorServicio;
            txtTotalContrato.setText(valorAcumulado.toString());
        }else{
             JOptionPane.showMessageDialog(this, "Debes seleccionar un servicio extra!");
        }
        
        
    }//GEN-LAST:event_btnAgregarServicioActionPerformed

    private void btnAgregarActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActividadActionPerformed
        Object selectedAct = JCBActividades.getSelectedItem();
        Actividadviaje act;
        if (selectedAct != null) {
            act  = (Actividadviaje) selectedAct ;
            ((DefaultListModel) lstActividades.getModel()).addElement(act);
            Integer valorActividad = act.getPrecio().intValueExact();
            Integer valorAcumulado = Integer.parseInt(txtTotalContrato.getText()) + valorActividad;
            txtTotalContrato.setText(valorAcumulado.toString());
        }else{
             JOptionPane.showMessageDialog(this, "Debes seleccionar un actividad extra!");
        }
        
    }//GEN-LAST:event_btnAgregarActividadActionPerformed

    private void txtTotalContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalContratoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalContratoActionPerformed

    private void btnQuitarActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActividadActionPerformed
        Object selectedAct = lstActividades.getSelectedValue();
        Actividadviaje act;
        if (selectedAct != null) {
            act  = (Actividadviaje) selectedAct ;
            DefaultListModel model = (DefaultListModel) lstActividades.getModel(); 
            int index = lstActividades.getSelectedIndex();
            model.remove( index );
            
            Integer valorActividad = act.getPrecio().intValueExact();
            Integer valorAcumulado = Integer.parseInt(txtTotalContrato.getText()) - valorActividad;
            txtTotalContrato.setText(valorAcumulado.toString());
            
        }else{
             JOptionPane.showMessageDialog(this, "Debes seleccionar un servicio a eliminar!");
        }
    }//GEN-LAST:event_btnQuitarActividadActionPerformed

    private void btnInsertContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertContratoActionPerformed
        Curso curso = (Curso) JCBCurso.getSelectedItem();
        Colegio col = (Colegio) JCBColegio.getSelectedItem();
        Paquete paquete = (Paquete) JCBPaquetes.getSelectedItem();
        ArrayList<Actividadviaje> actividadesArray = new ArrayList <>();
        for(int i = 0; i< lstActividades.getModel().getSize();i++){
            actividadesArray.add((Actividadviaje)lstActividades.getModel().getElementAt(i));
        }
        ArrayList<Servicio> serviciosArray = new ArrayList <>();
        for(int i = 0; i< lstServicios.getModel().getSize();i++){
            serviciosArray.add((Servicio)lstServicios.getModel().getElementAt(i));
        }
        ArrayList<Seguro> segurosArray = new ArrayList <>();
//        for(int i = 0; i< lstSeguros.getModel().getSize();i++){
//            segurosArray.add((Seguro)lstSeguros.getModel().getElementAt(i));
//        }
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        Date fecha = null;
        try {
             fecha = formatter.parse(txtDate.getText());
        } catch (ParseException ex) {
            Logger.getLogger(Contratos.class.getName()).log(Level.SEVERE, null, ex);
        }
        String cantDiasSt = JTFDias.getText();
        String cantAlumnosSt = JTFNumero.getText();
        String totalContrato = txtTotalContrato.getText();
        
        Boolean result = concon.insertContrato(curso,paquete,actividadesArray,serviciosArray,segurosArray,fecha,cantDiasSt,cantAlumnosSt,totalContrato,col);
        if (result) {
            JOptionPane.showMessageDialog(this, "Contrato salvado exitosamente!");
        }else{
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error, intente nuevamente!");
        }
        
    }//GEN-LAST:event_btnInsertContratoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBAgregarServicios1;
    private javax.swing.JComboBox<Actividadviaje> JCBActividades;
    private javax.swing.JComboBox<Servicio> JCBAgregarServicio;
    private javax.swing.JComboBox<Colegio> JCBColegio;
    private javax.swing.JComboBox<Comuna> JCBComuna;
    private javax.swing.JComboBox<Curso> JCBCurso;
    private javax.swing.JComboBox<Paquete> JCBPaquetes;
    private javax.swing.JComboBox<Region> JCBRegion;
    private javax.swing.JComboBox<Seguro> JCBSeguro;
    private javax.swing.JLabel JLTotal;
    private javax.swing.JTextField JTFDias;
    private javax.swing.JTextField JTFNumero;
    private javax.swing.JButton btnAgregarActividad;
    private javax.swing.JButton btnAgregarServicio;
    private javax.swing.JButton btnInsertContrato;
    private javax.swing.JButton btnQuitarActividad;
    private javax.swing.JButton btnQuitarServicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JList lstActividades;
    private javax.swing.JList lstSeguros;
    private javax.swing.JList lstServicios;
    private javax.swing.JFormattedTextField txtDate;
    private javax.swing.JTextField txtTotalContrato;
    // End of variables declaration//GEN-END:variables


    private void poblarListas() {
        cursocon = new CursoController();
        concon = new ContratoController();
       
        DefaultComboBoxModel regionModel = new DefaultComboBoxModel();
        JCBRegion.setModel(regionModel);
        JCBRegion.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent arg0) {
                actualizarComunas();
            }
        });
        
        JCBComuna.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent arg0) {
                actualizarColegios();
            }
        });
        
        JCBColegio.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent arg0) {
                actualizarCursos();
            }
        });
        cursocon.cargarComboRegion(JCBRegion);
        
        JCBPaquetes.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent arg0) {
                actualizarActividades();
                actualizarServicios();
                txtTotalContrato.setText(((Paquete)arg0.getItem()).getPrecio().toString());
            }
        });
        
        txtDate.setValue(new Date());
        DateFormatter df = new DateFormatter(new SimpleDateFormat("dd/MM/yyyy"));
        DefaultFormatterFactory factory = new DefaultFormatterFactory(); 
        factory.setDefaultFormatter(df); 
        JTFNumero.setDocument (new NumberValidator());
        JTFDias.setDocument (new NumberValidator());
        txtTotalContrato.setHorizontalAlignment(JTextField.RIGHT);
        txtDate.setFormatterFactory(factory);
        concon.cargarComboPaquetes(JCBPaquetes);
        concon.cargarComboActividades(JCBActividades);
        concon.cargarComboServicios(JCBAgregarServicio);
        
        
    }

    private void actualizarComunas() {
        Region region = (Region) JCBRegion.getSelectedItem();
        cursocon.actualizarComunas(region.getIdregion(), JCBComuna);
    }
    private void actualizarColegios() {
        Comuna comuna = (Comuna) JCBComuna.getSelectedItem();
        cursocon.actualizarComboColegios(comuna.getIdcomuna(),JCBColegio);
    }
    private void actualizarCursos() {
        Colegio colegio = (Colegio) JCBColegio.getSelectedItem();
        cursocon.actualizarCursos(colegio.getIdcolegio(), JCBCurso);
    }
    
    private void actualizarActividades() {
        Paquete paquete = (Paquete) JCBPaquetes.getSelectedItem();
        concon.cargarListaActividades(lstActividades,paquete.getIdpaquete());
    }
    
    private void actualizarServicios() {
        Paquete paquete = (Paquete) JCBPaquetes.getSelectedItem();
        concon.cargarListaServicios(lstServicios,paquete.getIdpaquete());
    }
    
    
}
