/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.duoc.ui;

import java.util.ArrayList;
import com.duoc.ui.AdministrarCuentas;
import com.duoc.ui.EstadoCuentaCurso;

/**
 *
 * @author Agustín
 */
public class DeskTravelMain extends javax.swing.JFrame {

    /**
     * Creates new form deskTravelMain
     */
    public DeskTravelMain() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public DeskTravelMain(ArrayList<?> usuario) {
        initComponents();
        this.setLocationRelativeTo(null);
        lblEstadoCuenta.setText("Bienvenido(a) " + usuario.get(0).toString() + " Perfil : " + usuario.get(1).toString());
    }

    public DeskTravelMain(String usuario, String idPerfil, String nombrePerfil) {
        initComponents();
        this.setLocationRelativeTo(null);
        lblEstadoCuenta.setText("Bienvenido(a) " + usuario + " Perfil : " + nombrePerfil);
        perfilar(idPerfil);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraEstado = new javax.swing.JPanel();
        lblEstadoCuenta = new javax.swing.JLabel();
        panelCentral = new javax.swing.JPanel();
        escritorio = new javax.swing.JDesktopPane();
        btnDesconectar = new javax.swing.JButton();
        barraMenuSuperior = new javax.swing.JMenuBar();
        mCursos = new javax.swing.JMenu();
        miRegistrarCurso = new javax.swing.JMenuItem();
        miEstadoCuenta = new javax.swing.JMenuItem();
        mContratos = new javax.swing.JMenu();
        miContratos = new javax.swing.JMenuItem();
        mTipos = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        mReportes = new javax.swing.JMenu();
        miReporteEstado = new javax.swing.JMenuItem();
        mCuentas = new javax.swing.JMenu();
        miMantenerCuenta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblEstadoCuenta.setText("Bienvenido Administrador - Juan Francisco ");

        javax.swing.GroupLayout barraEstadoLayout = new javax.swing.GroupLayout(barraEstado);
        barraEstado.setLayout(barraEstadoLayout);
        barraEstadoLayout.setHorizontalGroup(
            barraEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barraEstadoLayout.createSequentialGroup()
                .addGap(0, 492, Short.MAX_VALUE)
                .addComponent(lblEstadoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        barraEstadoLayout.setVerticalGroup(
            barraEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEstadoCuenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelCentralLayout = new javax.swing.GroupLayout(panelCentral);
        panelCentral.setLayout(panelCentralLayout);
        panelCentralLayout.setHorizontalGroup(
            panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio)
                .addContainerGap())
        );
        panelCentralLayout.setVerticalGroup(
            panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCentralLayout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29, Short.MAX_VALUE))
        );

        btnDesconectar.setText("Desconectar");
        btnDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesconectarActionPerformed(evt);
            }
        });

        barraMenuSuperior.setPreferredSize(new java.awt.Dimension(252, 20));

        mCursos.setText("Cursos");

        miRegistrarCurso.setText("Registrar Curso");
        miRegistrarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRegistrarCursoActionPerformed(evt);
            }
        });
        mCursos.add(miRegistrarCurso);

        miEstadoCuenta.setText("Estado de cuenta curso");
        miEstadoCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEstadoCuentaActionPerformed(evt);
            }
        });
        mCursos.add(miEstadoCuenta);

        barraMenuSuperior.add(mCursos);

        mContratos.setText("Contratos");

        miContratos.setText("Registrar Contrato");
        miContratos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miContratosActionPerformed(evt);
            }
        });
        mContratos.add(miContratos);

        barraMenuSuperior.add(mContratos);

        mTipos.setText("Tipos");

        jMenuItem1.setText("Mantener Tipos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mTipos.add(jMenuItem1);

        barraMenuSuperior.add(mTipos);

        mReportes.setText("Reportes");

        miReporteEstado.setText("Reporte de estado de avance");
        miReporteEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miReporteEstadoActionPerformed(evt);
            }
        });
        mReportes.add(miReporteEstado);

        barraMenuSuperior.add(mReportes);

        mCuentas.setText("Cuentas");

        miMantenerCuenta.setText("Mantener Cuentas");
        miMantenerCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miMantenerCuentaActionPerformed(evt);
            }
        });
        mCuentas.add(miMantenerCuenta);

        barraMenuSuperior.add(mCuentas);

        setJMenuBar(barraMenuSuperior);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(barraEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDesconectar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addComponent(panelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(barraEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDesconectar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miRegistrarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRegistrarCursoActionPerformed
        RegistrarCurso regcur = new RegistrarCurso(escritorio);
        escritorio.add(regcur);
        regcur.setVisible(true);
    }//GEN-LAST:event_miRegistrarCursoActionPerformed

    private void miEstadoCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEstadoCuentaActionPerformed
        EstadoCuentaCurso estcur = new EstadoCuentaCurso(escritorio);
        escritorio.add(estcur);
        estcur.setVisible(true);
    }//GEN-LAST:event_miEstadoCuentaActionPerformed

    private void btnDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesconectarActionPerformed
        Login log = new Login();
        log.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnDesconectarActionPerformed

    private void miMantenerCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miMantenerCuentaActionPerformed
        AdministrarCuentas admcuen = new AdministrarCuentas(escritorio);
        escritorio.add(admcuen);
        admcuen.setVisible(true);
    }//GEN-LAST:event_miMantenerCuentaActionPerformed

    private void miContratosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miContratosActionPerformed
                Contratos contra = new Contratos(escritorio);
                escritorio.add(contra);
                contra.setVisible(true);
    }//GEN-LAST:event_miContratosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void miReporteEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miReporteEstadoActionPerformed
                EstadoCuenta estadoCuenta = new EstadoCuenta();
                escritorio.add(estadoCuenta);
                estadoCuenta.setVisible(true);
    }//GEN-LAST:event_miReporteEstadoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraEstado;
    private javax.swing.JMenuBar barraMenuSuperior;
    private javax.swing.JButton btnDesconectar;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lblEstadoCuenta;
    private javax.swing.JMenu mContratos;
    private javax.swing.JMenu mCuentas;
    private javax.swing.JMenu mCursos;
    private javax.swing.JMenu mReportes;
    private javax.swing.JMenu mTipos;
    private javax.swing.JMenuItem miContratos;
    private javax.swing.JMenuItem miEstadoCuenta;
    private javax.swing.JMenuItem miMantenerCuenta;
    private javax.swing.JMenuItem miRegistrarCurso;
    private javax.swing.JMenuItem miReporteEstado;
    private javax.swing.JPanel panelCentral;
    // End of variables declaration//GEN-END:variables

    private void perfilar(String idPerfilSt) {
        int idPerfil = Integer.parseInt(idPerfilSt);
        if (idPerfil == 3) {
            mReportes.setEnabled(false);
            mCuentas.setEnabled(false);
        }else if(idPerfil == 6){
            mCursos.setEnabled(false);
            mContratos.setEnabled(false);
            mTipos.setEnabled(false);
            mCuentas.setEnabled(false);
        }
    }

}
