/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.java.com.duoc.ui;

import com.duoc.controller.AlumnoController;
import com.duoc.controller.CursoController;
import com.duoc.domain.Colegio;
import com.duoc.domain.Comuna;
import com.duoc.domain.Curso;
import com.duoc.domain.Pago;
import com.duoc.domain.Region;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.List;
import java.util.Vector;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author Agustín
 */
public class EstadoCuentaCurso extends javax.swing.JInternalFrame {

    CursoController cursocon;
    JDesktopPane escritorio;

    /**
     * Creates new form EstadoCuenta
     */
    public EstadoCuentaCurso() {
        initComponents();
    }

    public EstadoCuentaCurso(JDesktopPane escritorio) {
        this.escritorio = escritorio;
        initComponents();
        iniciarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFiltros = new javax.swing.JPanel();
        lblRegion = new javax.swing.JLabel();
        cmbRegion = new javax.swing.JComboBox<>();
        cmbComuna = new javax.swing.JComboBox<>();
        lblCOmuna = new javax.swing.JLabel();
        cmbColegio = new javax.swing.JComboBox<>();
        lblColegio = new javax.swing.JLabel();
        cmbCurso = new javax.swing.JComboBox<>();
        lblCurso = new javax.swing.JLabel();
        pnlResults = new javax.swing.JPanel();
        lblTotalAcumulado = new javax.swing.JLabel();
        lblMeta = new javax.swing.JLabel();
        txtTotalAcumulado = new javax.swing.JTextField();
        txtMeta = new javax.swing.JTextField();
        btnTerminar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listPagos = new javax.swing.JList<>();
        lblTitulo = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setNormalBounds(new java.awt.Rectangle(0, 0, 960, 500));
        setPreferredSize(new java.awt.Dimension(960, 500));

        lblRegion.setText("Región");

        cmbRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRegionActionPerformed(evt);
            }
        });

        lblCOmuna.setText("Comuna");

        lblColegio.setText("Colegio");

        cmbCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCursoActionPerformed(evt);
            }
        });

        lblCurso.setText("Curso");

        javax.swing.GroupLayout pnlFiltrosLayout = new javax.swing.GroupLayout(pnlFiltros);
        pnlFiltros.setLayout(pnlFiltrosLayout);
        pnlFiltrosLayout.setHorizontalGroup(
            pnlFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFiltrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlFiltrosLayout.createSequentialGroup()
                        .addComponent(lblRegion)
                        .addGap(18, 18, 18)
                        .addComponent(cmbRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblColegio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbColegio, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlFiltrosLayout.createSequentialGroup()
                        .addComponent(lblCOmuna)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbComuna, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCurso)
                        .addGap(18, 18, 18)
                        .addComponent(cmbCurso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFiltrosLayout.setVerticalGroup(
            pnlFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFiltrosLayout.createSequentialGroup()
                .addGroup(pnlFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegion)
                    .addGroup(pnlFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblColegio)
                        .addComponent(cmbColegio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCOmuna)
                    .addComponent(cmbComuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCurso)
                        .addComponent(cmbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 21, Short.MAX_VALUE))
        );

        lblTotalAcumulado.setText("Total Acumulado");

        lblMeta.setText("Meta");

        txtTotalAcumulado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalAcumuladoActionPerformed(evt);
            }
        });

        btnTerminar.setText("Terminar");
        btnTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(listPagos);

        javax.swing.GroupLayout pnlResultsLayout = new javax.swing.GroupLayout(pnlResults);
        pnlResults.setLayout(pnlResultsLayout);
        pnlResultsLayout.setHorizontalGroup(
            pnlResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResultsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(pnlResultsLayout.createSequentialGroup()
                        .addGroup(pnlResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlResultsLayout.createSequentialGroup()
                                .addGroup(pnlResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTotalAcumulado)
                                    .addComponent(lblMeta))
                                .addGap(88, 88, 88)
                                .addGroup(pnlResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMeta, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTotalAcumulado, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlResultsLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnTerminar)))
                        .addGap(0, 24, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlResultsLayout.setVerticalGroup(
            pnlResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlResultsLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotalAcumulado)
                    .addComponent(txtTotalAcumulado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMeta)
                    .addComponent(txtMeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTerminar)
                .addGap(55, 55, 55))
        );

        lblTitulo.setText("Estado de cuenta por Curso");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFiltros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlResults, javax.swing.GroupLayout.DEFAULT_SIZE, 944, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlResults, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnTerminarActionPerformed

    private void txtTotalAcumuladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalAcumuladoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalAcumuladoActionPerformed

    private void cmbRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRegionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRegionActionPerformed

    private void cmbCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCursoActionPerformed

    private void displayResult(List resultList) {
        Vector<String> tableHeaders = new Vector<String>();
        Vector tableData = new Vector();
        tableHeaders.add("Comuna");
        tableHeaders.add("Direccion");
        tableHeaders.add("IdColegio");
        tableHeaders.add("Nombre");

        for (Object o : resultList) {
            Colegio colegio = (Colegio) o;
            Vector<Object> oneRow = new Vector<Object>();
            //oneRow.add(colegio.getComuna());
            oneRow.add(colegio.getDireccion());
            oneRow.add(colegio.getIdcolegio());
            oneRow.add(colegio.getNombre());
            tableData.add(oneRow);
        }
        //tblResultado.setdomain(new DefaultTabledomain(tableData, tableHeaders));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTerminar;
    private javax.swing.JComboBox<Colegio> cmbColegio;
    private javax.swing.JComboBox<Comuna> cmbComuna;
    private javax.swing.JComboBox<Curso> cmbCurso;
    private javax.swing.JComboBox<Region> cmbRegion;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCOmuna;
    private javax.swing.JLabel lblColegio;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblMeta;
    private javax.swing.JLabel lblRegion;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTotalAcumulado;
    private javax.swing.JList<Pago> listPagos;
    private javax.swing.JPanel pnlFiltros;
    private javax.swing.JPanel pnlResults;
    private javax.swing.JTextField txtMeta;
    private javax.swing.JTextField txtTotalAcumulado;
    // End of variables declaration//GEN-END:variables

    private void iniciarComponentes() {
        cursocon = new CursoController();
        cursocon.cargarComboRegion(cmbRegion);
        cmbRegion.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent arg0) {
                actualizarComunas();
            }
        });
        cmbComuna.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent arg0) {
                actualizarColegios();
            }
        });
        cmbColegio.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent arg0) {
                actualizarCursos();
            }
        });
        cmbCurso.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent arg0) {
                cargarPagos();
            }
        });

    }

    private void actualizarComunas() {
        Region region = (Region) cmbRegion.getSelectedItem();
        cursocon.actualizarComunas(region.getIdregion(), cmbComuna);
    }

    private void actualizarColegios() {
        if (cmbComuna.getSelectedItem() != null) {
            Comuna comuna = (Comuna) cmbComuna.getSelectedItem();
            cursocon.actualizarComboColegios(comuna.getIdcomuna(), cmbColegio);
        }
    }

    private void actualizarCursos() {
        if (cmbColegio.getSelectedItem() != null) {
            Colegio colegio = (Colegio) cmbColegio.getSelectedItem();
            cursocon.actualizarCursos(colegio.getIdcolegio(), cmbCurso);
        }
    }

    private void cargarPagos() {
        if (cmbCurso.getSelectedItem() != null) {
            Curso curso = (Curso) cmbCurso.getSelectedItem();
            cursocon.cargarListaPagos(curso.getIdcurso(), listPagos);
        }
    }
}
