/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.duoc.ui;

import com.duoc.controller.CursoController;
import com.duoc.domain.Colegio;
import com.duoc.domain.Comuna;
import com.duoc.domain.Curso;
import com.duoc.domain.Region;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDesktopPane;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Agustín
 */
public class RegistrarCurso extends javax.swing.JInternalFrame {

    CursoController cursocon;
    JDesktopPane escritorio;

    /**
     * Creates new form RegistrarCurso
     */
    public RegistrarCurso() {

        initComponents();
        poblarListas();
    }

    RegistrarCurso(JDesktopPane aThis) {
        this.escritorio = aThis;
        initComponents();
        poblarListas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlColegio = new javax.swing.JPanel();
        lblTituloColegio = new javax.swing.JLabel();
        lblNombreColegio = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblComuna = new javax.swing.JLabel();
        txtDireccionColegio = new javax.swing.JTextField();
        txtNombreColegio = new javax.swing.JTextField();
        txtTelefonoColegio = new javax.swing.JTextField();
        cmbComunaColegio = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        btnAgregarColegio = new javax.swing.JButton();
        lblSelecColegio = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listColegios = new javax.swing.JList<>();
        lblRegion = new javax.swing.JLabel();
        cmbRegion = new javax.swing.JComboBox<>();
        pnlCurso = new javax.swing.JPanel();
        lblTituloCurso = new javax.swing.JLabel();
        lblNombreCurso = new javax.swing.JLabel();
        lblProfesorCurso = new javax.swing.JLabel();
        txtProfeCurso = new javax.swing.JTextField();
        txtNombreCurso = new javax.swing.JTextField();
        lblSelecCurso = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        listCursos = new javax.swing.JList<>();
        btnAgregarCurso = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setMaximumSize(new java.awt.Dimension(999999, 999999));
        setMinimumSize(new java.awt.Dimension(960, 440));
        setPreferredSize(new java.awt.Dimension(960, 460));

        pnlColegio.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblTituloColegio.setText("Crear colegio");

        lblNombreColegio.setText("Nombre:");

        lblDireccion.setText("Dirección:");

        lblTelefono.setText("Telefono:");

        lblComuna.setText("Comuna:");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnAgregarColegio.setText("Agregar");
        btnAgregarColegio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarColegioActionPerformed(evt);
            }
        });

        lblSelecColegio.setText("Seleccionar colegio");

        jScrollPane1.setViewportView(listColegios);

        lblRegion.setText("Región");

        cmbRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRegionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlColegioLayout = new javax.swing.GroupLayout(pnlColegio);
        pnlColegio.setLayout(pnlColegioLayout);
        pnlColegioLayout.setHorizontalGroup(
            pnlColegioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlColegioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlColegioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlColegioLayout.createSequentialGroup()
                        .addComponent(lblSelecColegio)
                        .addGap(0, 594, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlColegioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloColegio)
                    .addGroup(pnlColegioLayout.createSequentialGroup()
                        .addGroup(pnlColegioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreColegio)
                            .addComponent(lblDireccion)
                            .addComponent(lblComuna)
                            .addComponent(lblTelefono))
                        .addGroup(pnlColegioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlColegioLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(pnlColegioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTelefonoColegio, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(txtDireccionColegio)
                                    .addComponent(txtNombreColegio)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlColegioLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlColegioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbRegion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbComunaColegio, 0, 140, Short.MAX_VALUE)))))
                    .addComponent(btnAgregarColegio)
                    .addComponent(lblRegion))
                .addContainerGap())
        );
        pnlColegioLayout.setVerticalGroup(
            pnlColegioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(pnlColegioLayout.createSequentialGroup()
                .addComponent(lblSelecColegio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1))
            .addGroup(pnlColegioLayout.createSequentialGroup()
                .addComponent(lblTituloColegio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlColegioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreColegio)
                    .addComponent(txtNombreColegio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlColegioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccion)
                    .addComponent(txtDireccionColegio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(pnlColegioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefono)
                    .addComponent(txtTelefonoColegio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(pnlColegioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegion)
                    .addComponent(cmbRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlColegioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblComuna, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbComunaColegio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregarColegio))
        );

        pnlCurso.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblTituloCurso.setText("Crear curso");

        lblNombreCurso.setText("Nombre:");

        lblProfesorCurso.setText("Profesor Jefe:");

        lblSelecCurso.setText("Seleccionar curso");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jScrollPane2.setViewportView(listCursos);

        btnAgregarCurso.setText("Agregar");
        btnAgregarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCursoLayout = new javax.swing.GroupLayout(pnlCurso);
        pnlCurso.setLayout(pnlCursoLayout);
        pnlCursoLayout.setHorizontalGroup(
            pnlCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCursoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloCurso)
                    .addGroup(pnlCursoLayout.createSequentialGroup()
                        .addGroup(pnlCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreCurso)
                            .addComponent(lblProfesorCurso))
                        .addGap(23, 23, 23)
                        .addGroup(pnlCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtProfeCurso)
                            .addComponent(txtNombreCurso, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)))
                    .addComponent(btnAgregarCurso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(lblSelecCurso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE))
        );
        pnlCursoLayout.setVerticalGroup(
            pnlCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCursoLayout.createSequentialGroup()
                .addGroup(pnlCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloCurso)
                    .addComponent(lblSelecCurso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreCurso)
                    .addComponent(txtNombreCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProfesorCurso)
                    .addComponent(txtProfeCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(btnAgregarCurso)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCursoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                .addContainerGap())
        );

        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlColegio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSiguiente)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlColegio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSiguiente)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed

        Curso cur = listCursos.getSelectedValue();
        RegistroAlumno regal = new RegistroAlumno(cur);
        this.escritorio.add(regal);
        regal.show();
        this.hide();
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnAgregarColegioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarColegioActionPerformed
        String nombre = txtNombreColegio.getText();
        String direccion = txtDireccionColegio.getText();
        String telefono = txtTelefonoColegio.getText();
        Comuna comuna = (Comuna) cmbComunaColegio.getSelectedItem();
        Boolean result = cursocon.actualizarListaColegio(nombre, direccion, telefono, comuna, listColegios);
        if (result) {
            JOptionPane.showMessageDialog(this, "Colegio agregado correctamente");
        } else {
            JOptionPane.showMessageDialog(this, "Colegio no pudo ser agregado");
        }

    }//GEN-LAST:event_btnAgregarColegioActionPerformed

    private void btnAgregarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCursoActionPerformed
        String nombre = txtNombreCurso.getText();
        String profeJefe = txtProfeCurso.getText();
        Colegio col = listColegios.getSelectedValue();

        Boolean result = cursocon.actualizarListaCurso(nombre, profeJefe, col, listCursos);
        if (result) {
            JOptionPane.showMessageDialog(this, "Curso agregado correctamente");
        } else {
            JOptionPane.showMessageDialog(this, "Curso no pudo ser agregado");
        }
    }//GEN-LAST:event_btnAgregarCursoActionPerformed

    private void cmbRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRegionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRegionActionPerformed

    private void displayResult(List resultList) {
        Vector<String> tableHeaders = new Vector<String>();
        Vector tableData = new Vector();
        tableHeaders.add("Comuna");
        tableHeaders.add("Direccion");
        tableHeaders.add("IdColegio");
        tableHeaders.add("Nombre");

        for (Object o : resultList) {
            Colegio colegio = (Colegio) o;
            Vector<Object> oneRow = new Vector<Object>();
            //oneRow.add(colegio.getComuna());
            oneRow.add(colegio.getDireccion());
            oneRow.add(colegio.getIdcolegio());
            oneRow.add(colegio.getNombre());
            tableData.add(oneRow);
        }
        //tblResultado.setModel(new DefaultTableModel(tableData, tableHeaders));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarColegio;
    private javax.swing.JButton btnAgregarCurso;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JComboBox<Comuna> cmbComunaColegio;
    private javax.swing.JComboBox<Region> cmbRegion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblComuna;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblNombreColegio;
    private javax.swing.JLabel lblNombreCurso;
    private javax.swing.JLabel lblProfesorCurso;
    private javax.swing.JLabel lblRegion;
    private javax.swing.JLabel lblSelecColegio;
    private javax.swing.JLabel lblSelecCurso;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTituloColegio;
    private javax.swing.JLabel lblTituloCurso;
    private javax.swing.JList<Colegio> listColegios;
    private javax.swing.JList<Curso> listCursos;
    private javax.swing.JPanel pnlColegio;
    private javax.swing.JPanel pnlCurso;
    private javax.swing.JTextField txtDireccionColegio;
    private javax.swing.JTextField txtNombreColegio;
    private javax.swing.JTextField txtNombreCurso;
    private javax.swing.JTextField txtProfeCurso;
    private javax.swing.JTextField txtTelefonoColegio;
    // End of variables declaration//GEN-END:variables

    private void poblarListas() {
        cursocon = new CursoController();
        cursocon.cargarListaColegios(listColegios);
        DefaultComboBoxModel regionModel = new DefaultComboBoxModel();
        cmbRegion.setModel(regionModel);
        cmbRegion.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent arg0) {
                actualizarComunas();
            }
        });
        cursocon.cargarComboRegion(cmbRegion);

        ListSelectionListener listSelectionListener = new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent listSelectionEvent) {
                boolean adjust = listSelectionEvent.getValueIsAdjusting();
                if (!adjust) {
                    JList list = (JList) listSelectionEvent.getSource();
                    int selections[] = list.getSelectedIndices();
                    Object selectionValues[] = list.getSelectedValues();
                    for (int i = 0, n = selections.length; i < n; i++) {
                        Colegio col = (Colegio) selectionValues[i];
                        cursocon.cargarListaCursos(listCursos, col.getIdcolegio());
                    }
                }
            }
        };
        listColegios.addListSelectionListener(listSelectionListener);

        MouseListener mouseListener = new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent mouseEvent) {
                JList theList = (JList) mouseEvent.getSource();
                if (mouseEvent.getClickCount() == 2) {
                    int index = theList.locationToIndex(mouseEvent.getPoint());
                    if (index >= 0) {
                        Object o = theList.getModel().getElementAt(index);
                        System.out.println("Double-clicked on: " + o.toString());
                    }
                }
            }
        };
        listColegios.addMouseListener(mouseListener);
    }

    private void actualizarComunas() {
        Region region = (Region) cmbRegion.getSelectedItem();
        cursocon.actualizarComunas(region.getIdregion(), cmbComunaColegio);
    }

}
